AllCops:
  Exclude:
    - spec/data/**/*

AlignParameters:
  Enabled: false
ClassLength:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
CyclomaticComplexity:
  Max: 20
Documentation:
  Enabled: false
DoubleNegation:
  Enabled: false
GlobalVars:
  Enabled: false
Encoding:
  Enabled: false
HandleExceptions:
  Enabled: false
IfUnlessModifier:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ModuleFunction:
  Enabled: false
ParameterLists:
  Max: 6
RaiseArgs:
  Enabled: false
RedundantSelf:
  Enabled: false
RescueException:
  Enabled: false
SignalException:
  EnforcedStyle: only_raise
SpecialGlobalVars:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
TrivialAccessors:
  Enabled: false
StringLiterals:
  Enabled: false
