ClassAndModuleChildren:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Max: 20
Documentation:
  Enabled: false
GlobalVars:
  Enabled: false
Encoding:
  Enabled: false
HandleExceptions:
  Enabled: false
IfUnlessModifier:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ModuleFunction:
  Enabled: false
ParameterLists:
  Max: 6
RaiseArgs:
  Enabled: false
RescueException:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
TrivialAccessors:
  Enabled: false
